### PR TITLE
Complete captcha based on audio filename.

### PR DESCRIPTION
**Pull request by DrMeers**

### CODE REVIEW

**Comment by j-ro** [comment]
Hm...honestly, I'd rather keep this as a normal captcha, given that users are filling it out successfully and that's what phantom is more built to support. But happy to hear other arguments or take other thoughts.

**Comment by DrMeers** [comment]
Likewise, however we've been getting HTTP403 errors for the img src at http://www.crapo.senate.gov/contact/cfcontent.cfm for some reason...

**Comment by j-ro** [comment]
Huh...interesting, we're doing ok here, though this form is a bit flaky overall. Want to run this for a few days and report back on how well it works? After a bit of experience, maybe we'll all decide to merge?

**Comment by j-ro** [comment]
Tried this one myself for a few days, is working great! I already pushed it, so closing this without merging, but that is up there!

**Pull request closed without merging**
