### PR TITLE
Update M000303.yaml

### PR DESCRIPTION
**Pull request by Skekacs93**
Scroll to bottom of page to enable clicking on following buttons.

### CODE REVIEW

**Comment by j-ro** [comment]
Have you tested this? Typically scrolling is not necessary to click things, and I have successful fills on this yaml as is today, in the last hour, without scrolling.

**Comment by Skekacs93** [comment]
Strange, I was just running and getting:

WebDriverException: Message: unknown error: Element is not clickable at point (246, 512). Other element would receive the click: <div class="footer-follow">...</div>

**Comment by Skekacs93** [comment]
Scrolling fixed that for me though.

**Comment by j-ro** [comment]
That's a potentially different message -- like, that might indicate a modal pop up window or something like that.

**Comment by j-ro** [comment]
hm...well, I'll merge then -- scrolling isn't harmful, but odd that you need it and we don't.

**Pull request merged**
