### PR TITLE
rewrite of K000380.yaml

### PR DESCRIPTION
**Pull request by crdunwel**
Not sure how to handle the following:
screen shot 2015-02-02 at 4 20 37 pm

### CODE REVIEW

**Comment by j-ro** [comment]
generally, we're not putting non-required fields in yamls, so this (and issue) you can ignore. Also, generally we don't check subscription boxes. Do you want to resubmit? Or I can make those changes?

**Comment by crdunwel** [comment]
Oops sorry. Feel free to change it.

**Comment by j-ro** [comment]
cool, sounds good

**Comment by j-ro** [comment]
small note on this one (and on a few others): when rewriting make sure to check the success page, often the wording has changed, necessitating a changed success condition.

**Pull request merged**
