### PR TITLE
2021-08-11 - update T000476

### PR DESCRIPTION
**Pull request by jason44406**
Adds a missing field, and re-hides the recaptcha response field as it blocks the submit button.

### CODE REVIEW

**Comment by j-ro** [comment]
can we not hide that captcha response field, but rather move it? we need it visible

**Comment by jason44406** [comment]
Does it need to be visible the entire time?  There's a step prior to the `recaptcha` directive that makes it visible.  Once that step is complete, my addition re-hides it.  If that's still a problem, I can move it.

**Comment by j-ro** [comment]
I'm not sure what step the captcha solution comes in to the box, but it needs to be visible for that, so best to move it if we can.

**Comment by jason44406** [comment]
No problem.  Thanks for the discussion.

**Pull request merged**
