### PR TITLE
2020-01-22 - Update L000594

### PR DESCRIPTION
**Pull request by jason44406**
Hi guys.  I'm submitting this PR to remove the newly added GA Sen. Loeffler form because we can't seem to identify the success criteria.  When submitting with an incognito browser, the success message never appears, the page redirects to itself, and clears the fields without giving an indication that the form was accepted.  At this point, we're not sure if the form is really being accepted.  In my testing I've not received an email reply from the Senator's office in any circumstance, even when visiting the page and filling out the fields by hand.

I'd welcome a discussion on how we can consistently recognize a form success, as using a form for this Senator is the most desirable outcome, but not possible as is.

### CODE REVIEW

**Comment by j-ro** [comment]
I'd rather keep it and identify success by page reload (so look for the form again) even though it's not a great criteria, but I think it's ok for now.

**Comment by jason44406** [comment]
We'd have to change the success criteria text to be something that's always on the page.  My concern with that is there may be failures that we end up marking as success.

**Comment by j-ro** [comment]
Right, I think that would happen, but I think that's better than not having the form for now.

**Comment by chris-erickson** [comment]
Isn't an ambiguous condition essentially a failure?  We wouldn't consider a timeout to be a success, but for all intents, this is almost the same thing.  It also has the effect of being too open for other errors - the form changes and they redirect you someplace else and we consider that a success?

Perhaps I misunderstand what you mean by "look for the form again" but even so, seems like we're throwing the letter into the wind and calling it good because it left our hand.

We're probably going to start a parallel effort to get them to give us a less ridiculous form, but that can either be fast, or never happen 🤷‍♂

**Comment by j-ro** [comment]
Agree on all that but I think it’s better to submit some maybe than to not submit at all. We should keep an eye on the form for when it changes to better so we can update but I think we should leave something for now as it’s better than nothing.

**Comment by chris-erickson** [comment]
We heard back from a Senate contact, so seems like your intuition is right on.  Guess we'll plow bravely forward!

> It appears she still has a temporary website up (which is provided/facilitated directly by the Senate—as opposed to the contractors who design and service the full-featured, permanent ones).
>  
> That also means there’s a good chance all the messages, despite being ‘coded’ are dumping into a single outlook email account, and staff are (or are not) attempting to wade through it. [...]
>  
> My guess (barring any notice on security blocks like you’ve shared in the past) is that all your messages are going through, it’s just that they don’t have any auto response set up, and no one is sending outgoing responses….

**Comment by jason44406** [comment]
I updated the PR according to the conversation above, and included a comment in the code about the thoughts behind this. 
I intentionally made the success text a long text string -- hopefully if they update the form, they'll use something different enough to start failing the form so we can update.

**Comment by j-ro** [comment]
Thanks! I'll keep an eye on it ever few days too so hopefully we catch it when it changes.

**Pull request merged**
