### PR TITLE
Theses fixes make the forms work for me.

### PR DESCRIPTION
**Pull request by irjudson**

### CODE REVIEW

**Comment by j-ro** [comment]
I'll give these a try, but both of these are more successy on my end without this change.

**Comment by irjudson** [comment]
Let me know how you land -- I've written a python/phantomjs form processor using the same YAML; I'd like to stay on the same page for the YAML.

**Comment by j-ro** [comment]
reverted, as these are much worse after this merge

**Comment by irjudson** [comment]
You're using capybara in Rails for testing? I suspect selenium and capybara aren't behaving the same.

Thanks for the test -- hope it didn't cause grief.

**Comment by j-ro** [comment]
Yes, I believe so. No prob, happy to try!

**Comment by csnardi** [comment]
@j-ro Does P000603 still work with the reverted change? I ask because we see no successes with this YAML, which makes sense because it clicks the submit button once (success) and then a second time (now the success alert is gone, since none of the fields are filled in and it's replaced with a validation alert).

**Comment by j-ro** [comment]
I'm seeing consistent success with the current YAML on master, yes.

**Comment by csnardi** [comment]
@j-ro Hmm, I'm very surprised to hear that. I'd almost suggest running another test for P000603, since we really would prefer not to fork this file in case it diverges, but I wouldn't want to possibly disrupt your message sending.

**Comment by j-ro** [comment]
We're delivering thousands every day -- it's very much working.

**Comment by csnardi** [comment]
My confusion is because it shouldn't be -- try filling out the form in your browser, and then performing the steps (`document.querySelector("#edit-submit--2").click()`, wait 5 seconds, `document.querySelector("#edit-submit--2").click()`). You should get a failure message, which is why I find it really odd this is succeeding.

Probably something we'll just have to make an exception for, and I should stop pestering you, I'm just shocked it actually is working for someone. 😕

**Comment by j-ro** [comment]
Yeah, for sure -- there are quite a few yamls in this repo that differ from how you'd actually fill them out in a browser however. Probably has something to do with the recaptcha as well, if I'm guessing. But it certainly works for us on our engine (https://github.com/EFForg/phantom-of-the-capitol) so if you're using something significantly different, you may need a fork for a few unfortunately.

**Pull request merged**
