### PR TITLE
Update T000461.yaml, C001098.yaml, M000133.yaml, P000449.yaml

### PR DESCRIPTION
**Pull request by amy-chinlai**
Added javascript step to make recaptcha visible

### CODE REVIEW

**Comment by chris-erickson** [comment]
What was the reasoning for this?  It's exposing this field over the top of submit buttons and making them unclickable:

Screen Shot 2019-09-17 at 3 41 11 PM

Can we revert this?

/cc @jason44406

**Comment by j-ro** [comment]
This is necessary for our recaptcha implementation to work correctly. You can kill css styles on the page if you want, that typically helps with positioning issues.

**Comment by chris-erickson** [comment]
Can you help us understand how we'd alter the CSS when we're using this form config as-is?  It seems counterproductive to introduce layout changes that break the ability to click submit, no?  Could this be done in a way that doesn't cause that element to be _over_ the button, but push it down?

**Comment by j-ro** [comment]
you'd add something to the yaml like this to kill form styles: https://github.com/unitedstates/contact-congress/blob/9cbf5ace3efaa823508527cafee0bd1bb83fd6a6/members/D000624.yaml#L8

**Comment by chris-erickson** [comment]
Are you suggesting we update _your_ yaml's to have something like this when they use JS to show an invisible element?  Sorry if I'm not following but we use them with zero modification from CC and have no way to extend or manipulate them besides just forking them internally which seems like an unfortunate thing to require if you want to click submit.

**Comment by j-ro** [comment]
I'm suggesting you submit a PR to this yaml (and any others necessary) adding in some javascript to remove styles. Removing styles should work for everyone, so happy to have that on the main yaml file.

**Comment by jason44406** [comment]
I will do so.  Thanks.

**Comment by jason44406** [comment]
Hey @j-ro,
Just stripping out the CSS still gives me an issue with the one element overlaying the other.  (see below.)  However, if I slide the response textarea down a bit with a topMargin, it resolves the conflict.

Questions:
1 - Would it be acceptable to move the textarea down to prevent overlaying elements?
2 - Would you will like the CSS stripped for affected yamls as well?  

Thanks.
image

**Comment by j-ro** [comment]
Top margin is fine, whatever works really. Typically no CSS fixes layout issues but maybe there's some inline stuff here that doesn't get stripped. No need to strip CSS if it's not fixing your issue.

**Pull request merged**
