### PR TITLE
R000599.yaml form change

### PR DESCRIPTION
**Pull request by crdunwel**

### CODE REVIEW

**Comment by j-ro** [comment]
I can't get this one to work. I get the error:

```
[
{
"status": "error",
"error": "undefined local variable or method `e' for #<CongressMember:0x000000044744e8>\n[\"/var/www/apps/congress-forms/app/models/congress_member.rb:51:in `rescue in fill_out_form'\", \"/var/www/apps/congress-forms/app/models/congress_member.rb:39:in `fill_out_form'\", \"/var/www/apps/congress-forms/app/helpers/form_fill_handler.rb:15:in `block in create_thread'\"]",
"run_at": "2015-01-20T18:43:31+00:00",
"screenshot": "https://can2-dev.s3.amazonaws.com/development/screenshots/ea18b395aac64947e1c5ad2f69.png"
}
]
```

Which typically means that the options in the select menu on the yaml don't match what's actually on the page. And indeed, it's the state select input that causes the failure (taking it out causes the form to be completely filled except for state, and of course that triggers a validation error).

But I can't figure out what's wrong with the state input section in the yaml. Tried a few things over a few commits, all ended up the same.

You seeing the same? Any thoughts?

**Comment by crdunwel** [comment]
My test framework is less robust than yours (it's just using the code to send a letter and checking if it succeeds) so, for instance, if a topic option doesn't exist then it will pick a random one and thus still succeed.

**Comment by j-ro** [comment]
gotcha. I'll dig in more and see if I can fix this one.

**Comment by j-ro** [comment]
got it working! the state ID is actually duplicated on the page (and in the form!), so changed the selector, and noting that this error can mean duplicates for next time.

**Pull request merged**
