### PR TITLE
Delete old and unused forms

### PR DESCRIPTION
**Pull request by csnardi**
This was generated by running through the files and seeing if their ID was in the list of current representatives from https://theunitedstates.io/congress-legislators/legislators-current.json. I also deleted the version of C001056.yaml that was not in the members/ folder as it does not appear to be maintained.

### CODE REVIEW

**Comment by j-ro** [comment]
Thanks! I'll admit to being fairly nervous about deletes, since if we miss one production systems might not notice for a while. I'm willing to merge it though after a bit of discussion from others.

Also we should keep C001056 outside of the members folder, it's linked to in the readme as an example of the format, for contributors.

**Comment by csnardi** [comment]
I agree about being nervous about deletes, so I made sure to verify that there all legislators in `legislators-current.json` had a file in this repo (they did), and that the count of legislators equals the count of files in `members/` (it does). I'm fine with waiting a bit though.

I also tried to look for any references to C001056 in the repo, and couldn't find any (though it's certainly possible that I missed it).

**Comment by j-ro** [comment]
I think another good test might be are there 100 yamls that have senate.gov in their starting urls, that would confirm we have all the Senate members, which is all this repo is used for these days given CWC is used for the House.

**Comment by csnardi** [comment]
```
Searching 534 files for "senate.gov"
(snip)
128 matches across 100 files
```

**Comment by j-ro** [comment]
Nice! Ok, let's give this a few days for more feedback, and if you can keep that non /members file, then I think we're good.

**Comment by csnardi** [comment]
I can add back the file, but I just couldn't find any references to it (e.g. by https://github.com/unitedstates/contact-congress/search?q=C001056&unscoped_q=C001056 or a manual search of both the `master` and `gh-pages` branches locally).

**Comment by j-ro** [comment]
It's in a few external websites I believe, though not in this repo.

**Comment by j-ro** [comment]
Thanks, I'll aim to merge midweek.

**Pull request merged**
