### PR TITLE
[C001047] javascript submit with delay

### PR DESCRIPTION
**Pull request by rubbingalcoholic**
This is the new form for Shelley Moore Capito with fixes to resolve the stability issues on my instance of phantom-of-the-capitol. It seems the trick was to submit via javascript and delay before searching for the success_hash.

### CODE REVIEW

**Comment by j-ro** [comment]
actually, probably better would be a find instead of a wait? That's what we usually do for forms like that that submit a bit ajax-y

**Comment by rubbingalcoholic** [comment]
There is nothing useful to "find" in the AJAX confirmation message though. The form is dynamically replaced with this:
```
<div><h1>Thank You</h1>
<p>Thank you for submitting your Request to our office.</p>
<p>We will contact you if we need any additional information.</p>
<p>Sincerely,</p>
<p><i>The Office of Senator Shelley Moore Capito </i></p></div>
```
I'm not sure of any selector I could apply here without hitting something else already on the page.

**Comment by j-ro** [comment]
you should be able to do something like:

```
find:
  selector: "h1"
  value: "Thank You"
```

you can combine selectors and values.

**Comment by rubbingalcoholic** [comment]
This is tested working.

**Pull request merged**
