### PR TITLE
remove quotes from message

### PR DESCRIPTION
**Pull request by anselmoalves**

### CODE REVIEW

**Comment by crdunwel** [comment]
What's the rational for trying to clean the user input data here in javascript rather than in the application?

**Comment by j-ro** [comment]
Two reasons. 

One, it's not uniform -- I don't get these messages when I fill out forms by hand. There's some algorithmic firewalling going on. So this is a lightweight solution that doesn't involve app changes for those who don't need it.

Two, it changes often -- this wasn't a problem until recently, and I'd expect there are other rules we'll discover, so we'll want to implement them as well. Instead of building a new app feature every time, we can just do javascript, which is the point of the javascript implementation.

**Comment by crdunwel** [comment]
It does create extra work when things change but I guess there is a benefit to adding some scrubbing/formatting in the instructions if the javascript engine is there anyways.

**Comment by j-ro** [comment]
Sure, and it's a pretty easy script to make mass changes. These files weren't all hand edited.

**Comment by crdunwel** [comment]
Yeah I'm just thinking when a selector changes then it has to be updated multiple places so less DRY. People should be doing find/replace all on these but people aren't perfect. So just saying, this pattern will add complexity to the instructions that may introduce more human error. I think the tradeoff might be worth it though since less worrying about scrubbing in the consuming applications.

**Comment by j-ro** [comment]
Yeah, good point. I think the trade off is worth it though, especially in the flexibility. They are actively changing their firewall rules (we were completely blocked the other week) and I expect that to continue. So being able to respond quickly in yaml without new app features seems important.

**Comment by crdunwel** [comment]
:+1:

**Pull request merged**
