### PR TITLE
Add max_length attribute to the schema

### LINKED ISSUE #1454: Fill_In Max length attribute
Sen. Roy Blunt and Rep. Bob Dold have a maximum length limit on their message boxes, although you'd only know after the message gets rejected on their server. To accommodate this restriction in the YAML, I was thinking it could be as simple as adding a `max_length` attribute to `fill_in`. Our apps could then truncate as needed.

Thoughts?

### PR DESCRIPTION
**Pull request by kthayer424**
For fill_in fields to resolve #1454.

### CODE REVIEW

**Comment by j-ro** [comment]
worth noting that this should be an integer, and that the number represents characters?

**Comment by kthayer424** [comment]
Boom!

**Comment by j-ro** [comment]
works for me! Any other comments from folks?

**Comment by j-ro** [comment]
So, been a few days, no comments. Thoughts from anyone on how we should handle merging?

I guess my concern here is that until phantom-dc is updated to include this new change, I think YAMLs with this directive will fail. And since we pull from this repo....

Probably a good point to discuss how we handle these things more generally too. Thoughts?

**Comment by sinak** [comment]
Yeah tricky one. @Hainish do you have time to update congress-forms to add this directive?

But on how we handle this more generally ... maybe its time we created branches for each implementation? So we could have a master branch that is most up to date, and then a phantom-dc branch that is up to date with the latest spec supported by phantom-dc?

**Comment by Hainish** [comment]
I'll work on implementing this within Phantom DC now.

**Comment by j-ro** [comment]
Branches are helpful, yes. I also think generally might be good for phantom-dc to ignore directives it doesn't understand as opposed to erroring. That way our spec can keep evolving while our tools catch up.

**Comment by Hainish** [comment]
@j-ro the current behavior *is* to ignore directives it doesn't understand.  It never imports them into the database at all.

This is ensured by the conditional [here](https://github.com/EFForg/phantom-of-the-capitol/blob/master/tasks/phantom-dc.rake#L401).

**Comment by j-ro** [comment]
Oh, gotcha -- well, I'll want to test it with our version, but that's great. Then I think we can indeed merge this, no real issues.

**Comment by kthayer424** [comment]
@j-ro How's that?

**Comment by j-ro** [comment]
merged! woot!

**Pull request merged**
