### PR TITLE
2022-10-18 - S001194 remove recaptcha

### PR DESCRIPTION
**Pull request by jcachia**
Removes the recaptcha on S001194 - Schatz

Note, I've merged my two github accounts - I previously used @jason44406 , but will be using this account from now on.  Thanks.

### CODE REVIEW

**Comment by j-ro** [comment]
The recaptcha is still on this form I think? It's a hidden one, hence the javascript we add to make that work, but I think that's still necessary?

**Comment by jcachia** [comment]
> The recaptcha is still on this form I think? It's a hidden one, hence the javascript we add to make that work, but I think that's still necessary?

I'm not sure.  When I removed the those lines and ran the yaml through our stuff, it was successfully sent.  When I leave those lines in to trigger the recaptcha, we can't find the sitekey needed to solve the recaptcha.

**Comment by j-ro** [comment]
Hm, we're all successes over here with the current yaml, and seeing captcha stuff on the page in view source. Perhaps you get served a different source, but I don't think we can merge this.

**Comment by jcachia** [comment]
> Hm, we're all successes over here with the current yaml, and seeing captcha stuff on the page in view source. Perhaps you get served a different source, but I don't think we can merge this.

Ok, yeah we dont want to break anything.  I think we're failing 100%, so I'll look to see what we can do.

**Pull request closed without merging**
