### PR TITLE
2019-07-22 Update C001056

### PR DESCRIPTION
**Pull request by jason44406**
Updated C001056 form.

### CODE REVIEW

**Comment by j-ro** [comment]
I think you're going to need some finds between each of those steps for this to work correctly. Want to add those?

**Comment by jason44406** [comment]
I will add some.  Thanks for the feedback.  The stuff I am using to interact with the forms has a default wait time until the elements become clickable, so it all works when I test it.

**Comment by jason44406** [comment]
@j-ro 

I added some find directives anywhere a page load completion is required to interact with the next element.

**Comment by j-ro** [comment]
thanks!

**Pull request merged**
