### PR TITLE
Close newsletter signup overlay on Hassan's form

### PR DESCRIPTION
**Pull request by csnardi**
Hassan's form added a newsletter signup which covers part of the page. Close this overlay before attempting to proceed with the form.

### CODE REVIEW

**Comment by j-ro** [comment]
I usually use the remove CSS files technique instead of clicking to close -- less error prone, in case that click fails. With no CSS there's no overlays, so you don't get errors filling.

**Comment by csnardi** [comment]
Hm, I'm finding that the stylesheet removal version isn't working since the image seems to capture any clicks intended for the actual form. I'd think that the close button solution might be better, as it avoids this and also keeps the page from being very jumbled when trying to identify errors.

**Comment by j-ro** [comment]
We found consistent errors with the close button, since we weren't seeing the newsletter overlay at all most of the time. Without styles it's impossible for images to overlay forms, and we're seeing consistent successes now.

**Comment by csnardi** [comment]
Interesting, I wouldn't expect that since that's not what I can reproduce in my own browser. If I go to https://www.hassan.senate.gov/contact/email and run `Array.prototype.forEach.call(document.querySelectorAll('style,[rel=\"stylesheet\"],[type=\"text/css\"]'), function(element){ try{ element.parentNode.removeChild(element) } catch(err){} });`, I can't click on any of the fields without getting scrolled away.

**Comment by j-ro** [comment]
Huh...maybe browser differences? On Chrome on Mac I have no problem clicking fields....

But anyway, maybe javascript is our solution here, since if that errors it's no issue. Something like:

```
document.getElementById('newsletterModal').remove()
```

**Comment by csnardi** [comment]
Oh, yeah, good idea. It looks like the element fades in, but is always present in the HTML. So that should always prevent the modal from showing up.

**Comment by j-ro** [comment]
alright, wanna do a pr? if not I can tomorrow

**Comment by csnardi** [comment]
Sure, went ahead and created #1691.

**Pull request merged**
